definitions:
  defaultError:
    type: object
    properties:
      data:
        type: object
        example: null;
      isBoom:
        type: boolean
        example: true;
      isServer:
        type: boolean
        example: true;
      output:
        type: object
        properties:
          statusCode:
            type: number
            example: 500
          payload:
            type: object
            properties:
              statusCode:
                type: number
                example: 500
              error:
                type: string
                example: "Internal Server Error"
              message:
                type: string
                example: "risos"
          headers:
            type: object